import { ArrowRight, Badge, Eye, EyeOff, LockKeyhole } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { useAuth } from "../../auth/AuthContext";

export default function AdminLogin(){
  const [form,setForm]=useState({email:"",password:""}); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const navigate=useNavigate(); const {adminLogin}=useAuth();
  const submit=async e=>{e.preventDefault();setBusy(true);try{const r=await adminLogin(form.email,form.password);if(r?.user?.role && !["ADMIN","SUPER_ADMIN","MAIN_ADMIN"].includes(r.user.role)) throw new Error("This account does not have administrator access."); navigate("/admin",{replace:true});}catch(err){window.dispatchEvent(new CustomEvent("nfc:toast",{detail:{message:err.message,type:"error"}}));}finally{setBusy(false)}};
  return <div className="login-page"><div className="login-brand"><div className="brand-mark large"><Badge size={25}/></div><div><strong>NFC Connect</strong><span>Administrator access</span></div></div><form className="login-card" onSubmit={submit}><div className="login-icon"><LockKeyhole size={22}/></div><div className="eyebrow">ADMIN PORTAL</div><h1>Administrator sign in</h1><p className="login-copy">Use your administrator account to manage users, cards and provisioning.</p><label className="field"><span>Email</span><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} autoComplete="username"/></label><label className="field"><span>Password</span><div className="password-field"><input type={show?"text":"password"} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="current-password"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><button className="btn btn-primary btn-wide" disabled={busy}>{busy?"Signing in…":<>Sign in to admin <ArrowRight size={17}/></>}</button><p className="auth-switch"><Link to="/">← Back to main website</Link> · <Link to="/login">User sign in</Link></p></form></div>;
}
