import { Search, UserPlus, X, Check, CreditCard, Power, Trash2, Eye } from "lucide-react";
import { Link } from "react-router-dom";
import Layout from "../../components/Layout";
import PageHeader from "../../components/PageHeader";
import StatusBadge from "../../components/StatusBadge";
import { useEffect,useMemo,useState } from "react";
import { api } from "../../services/api";

export default function AdminUsers(){
  const[users,setUsers]=useState([]);const[q,setQ]=useState("");const[show,setShow]=useState(false);const[form,setForm]=useState({name:"",email:""});const[created,setCreated]=useState(null);const[busy,setBusy]=useState(null);const[deleteUser,setDeleteUser]=useState(null);
  const load=async()=>{try{const r=await api.adminUsers();setUsers(r.users||[])}catch{}};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>users.filter(u=>u.role==="USER" && `${u.name} ${u.email}`.toLowerCase().includes(q.toLowerCase())),[users,q]);
  const create=async e=>{e.preventDefault();try{const r=await api.createAdminUser(form);setCreated(r);setForm({name:"",email:""});await load()}catch{}};
  const toggle=async u=>{setBusy(u.id);try{if(u.status==="DISABLED")await api.enableUser(u.id);else await api.disableUser(u.id);await load();window.dispatchEvent(new CustomEvent("nfc:toast",{detail:{message:u.status==="DISABLED"?"User enabled.":"User disabled.",type:"success"}}))}catch{}finally{setBusy(null)}};
  const removeUser=async()=>{if(!deleteUser)return;setBusy(deleteUser.id);try{await api.deleteAdminUser(deleteUser.id);setDeleteUser(null);await load();window.dispatchEvent(new CustomEvent("nfc:toast",{detail:{message:"User account deleted.",type:"success"}}))}catch{}finally{setBusy(null)}};
  return <Layout admin><PageHeader eyebrow="ADMINISTRATION / USERS" title="User management" description="Maintain user accounts, control access and review card activity." action={<button className="btn btn-primary" onClick={()=>{setShow(true);setCreated(null)}}><UserPlus size={17}/> Add user</button>}/>
    <section className="panel info-strip"><div className="strip-icon"><CreditCard size={18}/></div><div><strong>Account access is controlled here.</strong><span>When a user is disabled, the backend must block login and public-card access. The user cannot override an administrator ban.</span></div><Link className="btn btn-secondary" to="/admin/cards">Manage cards</Link></section>
    <section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search users..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{filtered.length} users</span></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Cards</th><th>Status</th><th>Details</th><th>Access</th><th>Delete user</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id||u._id}><td><div className="table-card"><div className="avatar small">{u.name?.slice(0,1)}</div><div><strong>{u.name}</strong><small>{u.email}</small></div></div></td><td>{u.cards ?? 0}</td><td><StatusBadge status={u.status}/></td><td><Link className="btn btn-small btn-secondary" to={`/admin/users/${u.id||u._id}`}><Eye size={14}/> View</Link></td><td><button className={`btn btn-small ${u.status==="DISABLED"?"btn-success-soft":"btn-danger-soft"}`} disabled={busy===u.id} onClick={()=>toggle(u)}><Power size={14}/>{u.status==="DISABLED"?"Enable user":"Disable user"}</button></td><td><button className="icon-btn danger" disabled={busy===u.id} onClick={()=>setDeleteUser(u)} title="Delete user" aria-label={`Delete ${u.name||"user"}`}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div></section>
    {deleteUser&&<div className="modal-backdrop delete-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDeleteUser(null)}><div className="confirm-modal"><div className="confirm-icon"><Trash2 size={22}/></div><h2>Delete this user?</h2><p>This permanently removes the user account from the admin system. This action should only be used when the account must be removed rather than temporarily disabled.</p><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setDeleteUser(null)}>Cancel</button><button className="btn btn-danger-soft" onClick={removeUser} disabled={busy===deleteUser.id}>Delete user</button></div></div></div>}
    {show&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><div className="modal"><div className="modal-header"><div><span className="eyebrow">NEW ACCOUNT</span><h2>Create user</h2><p>The backend generates a temporary password and returns it once.</p></div><button className="icon-btn" onClick={()=>setShow(false)}><X size={20}/></button></div>{created?<><div className="success-box"><Check size={22}/><div><strong>{created.user?.name||"User"} created</strong><span>{created.user?.email} · Temporary password: <code>{created.temporaryPassword}</code></span></div></div><div className="modal-actions"><button className="btn btn-primary" onClick={()=>setShow(false)}>Done</button></div></>:<form onSubmit={create}><label className="field"><span>Full name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Email</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary">Create account</button></div></form>}</div></div>}
  </Layout>
}